 ## THIRUMALA LAXMI TANUJA


In [495]:
# Download the data locally

import os
from urllib.request import urlretrieve
import gzip

# download the data if we don't have it locally
url = "http://faculty.cs.niu.edu/~dakoop/cs640-2023sp/a1/aam-salary-survey.csv.gz"
local_fname = "aam-salary-survey.csv.gz"
if not os.path.exists(local_fname):
    urlretrieve(url, local_fname)

In [496]:
local_fname

'aam-salary-survey.csv.gz'

## 1. Reformatting the Salary column

In [497]:
import pandas as pd
df = pd.read_csv("aam-salary-survey.csv.gz")
df['Salary'] = df['Salary'].str.replace(',', '').astype(float)

## 2. Updating the Range Columns

In [498]:
# df.iloc[:3]

In [499]:
# updating age column
# Split the Age column into left and right endpoints
df['Age'] = df['Age'].replace({'under ': '0-', 'less than': '0-', 'or over': '- 999'}, regex=True)
endpoints = df['Age'].str.split('-', expand = True)
# Convert the left and right endpoints to numeric data types
left_endpoints = endpoints[0].astype(int)
right_endpoints = endpoints[1].astype(int)
right_endpoints = right_endpoints + 1
# Create an IntervalArray from the left and right endpoints
interval_array = pd.arrays.IntervalArray.from_arrays(left_endpoints, right_endpoints, closed='left')
df = df.assign (Age = interval_array)

In [500]:
df.Age.array.overlaps(pd.Interval(18,45, closed='left'))

array([ True,  True,  True, ...,  True,  True,  True])

In [501]:
# updating ExpOverall and ExpInField
def create_range_intervale(df, col):
    df[col] = df[col].replace({'1 year or less': '0-1', 'years or more' : '-999'}, regex=True)
    endpoints = df[col].str.split('-', expand = True)
    # Convert the left and right endpoints to numeric data types
    left_endpoints = endpoints[0].astype(int)
    right_endpoints = endpoints[1].str.extract('(\d+)', expand = False).astype(int)
    right_endpoints = right_endpoints + 1

    # Create an IntervalArray from the left and right endpoints
    interval_array = pd.arrays.IntervalArray.from_arrays(left_endpoints, right_endpoints, closed='left')
    df[col] = interval_array
    return df
      

In [502]:
df = create_range_intervale(df, 'ExpOverall')
df = create_range_intervale(df, 'ExpInField')

In [503]:
df.ExpOverall.array.overlaps(pd.Interval(18,45, closed='left'))

array([False, False, False, ...,  True, False,  True])

In [504]:
df.ExpInField.array.overlaps(pd.Interval(18,45, closed='left'))

array([False, False, False, ...,  True, False, False])

## 3. Combine and Clean the Currency Columns

In [505]:
import pandas as pd
import numpy as np
excel_df = pd.read_excel('list-one.xls')
# excel_df

In [506]:
other_currency = df['CurrencyOther']
pattern = r'\b([A-Z]{3})\b'
other_currency = other_currency.str.extract(pattern, expand = True)
other_currency = other_currency.rename(columns = {0 : 'curr'})
other_currency['is_in_codes'] = other_currency['curr'].isin(excel_df['Unnamed: 2'])
other_currency.loc[other_currency['is_in_codes'] == False, 'curr'] = np.nan
# other_currency

In [507]:
df['Currency'] = df['Currency'].where(df['Currency'] != 'Other', other_currency['curr'])
df = df.drop('CurrencyOther', axis = 1)
# df[df['Currency'] == "Other"]

## 4. Salary Cleaning

In [508]:
# df[(df['Currency'] == 'USD') & (df['Salary'] > 2 ) & (df['Salary'] < 500)]


In [509]:
# """The reason why the salaries are very low is people might gave hourly income or weekly or monthly rather than yearly.
# we can check the avg income based on the job role and designation and if the salary is very low, then it might me an error.
# for this assignment, I am assuming that people might enter their pay rate in different freq and I am conevrting them to anual income.
# """

In [510]:
# df['Salary'].mean()

In [511]:
# df.loc[(df['Currency'] == 'USD') & (df['Salary'] != 0 ), 'Salary'] .mean()

In [512]:
# replacing the column values with mean if 0
df.loc[(df['Currency'] == 'USD') & (df['Salary'] == 0 ), 'Salary'] = 96478.81265583355
# assuming minimun hourly wage is 7, so replcaing values less than 7 with 7 as hourly income
df.loc[(df['Currency'] == 'USD') & (df['Salary'] <= 7 ), 'Salary'] *= (2080 * 7)
# Assuming below ranges and converting them to annual income.
df.loc[(df['Currency'] == 'USD') & (df['Salary'] > 80 ) & (df['Salary'] <= 160), 'Salary'] *= 2080
df.loc[(df['Currency'] == 'USD') & (df['Salary'] > 8 ) & (df['Salary'] <= 80), 'Salary'] *= 52
df.loc[(df['Currency'] == 'USD') & (df['Salary'] > 160 ) & (df['Salary'] <= 400), 'Salary'] *= 24
df.loc[(df['Currency'] == 'USD') & (df['Salary'] > 400 ) & (df['Salary'] <= 500), 'Salary'] *= 12


In [514]:
df

Timestamp       Age                       Industry  \
0       4/27/2021 11:02:10  [25, 35)   Education (Higher Education)   
1       4/27/2021 11:02:22  [25, 35)              Computing or Tech   
2       4/27/2021 11:02:38  [25, 35)  Accounting, Banking & Finance   
3       4/27/2021 11:02:41  [25, 35)                     Nonprofits   
4       4/27/2021 11:02:42  [25, 35)  Accounting, Banking & Finance   
...                    ...       ...                            ...   
27920  12/22/2022 17:43:19  [25, 35)                  Entertainment   
27921   12/29/2022 7:54:18  [55, 65)                    Health care   
27922     1/4/2023 9:11:41  [35, 45)                         Retail   
27923    1/8/2023 12:16:15  [18, 25)              Computing or Tech   
27924   1/11/2023 16:25:11  [35, 45)                        student   

                                       JobTitle  \
0            Research and Instruction Librarian   
1      Change & Internal Communications Manager   
2                          Marketing Specialist   
3                               Program Manager   
4                            Accounting Manager   
...                                         ...   
27920                                   Analyst   
27921              Physical therapist assistant   
27922            Marketing Automation Developer   
27923                        Computer Scientist   
27924                      data science student   

                                            JobDetails        Salary  \
0                                                  NaN  55000.000000   
1                                                  NaN  54600.000000   
2                                                  NaN  34000.000000   
3                                                  NaN  62000.000000   
4                                                  NaN  60000.000000   
...                                                ...           ...   
27920  Analyst in A&R Admin Department at record label  60000.000000   
27921                                      Home health  62400.000000   
27922                                              NaN  68000.000000   
27923                                              NaN  10000.000000   
27924                                              NaN  96478.812656   

       ExtraComp Currency      IncomeDetails         Country           State  \
0            0.0      USD                NaN   United States   Massachusetts   
1         4000.0      GBP                NaN  United Kingdom             NaN   
2            NaN      USD                NaN              US       Tennessee   
3         3000.0      USD                NaN             USA       Wisconsin   
4         7000.0      USD                NaN              US  South Carolina   
...          ...      ...                ...             ...             ...   
27920        NaN      USD                NaN   United States        New York   
27921        NaN      USD                NaN             Usa        Colorado   
27922        NaN      USD                NaN   United States         Indiana   
27923        NaN      TRY                NaN          Turkey             NaN   
27924     8500.0      USD  housing allowance             USA           Texas   

              City ExpOverall ExpInField        Education      Gender  \
0           Boston     [5, 8)     [5, 8)  Master's degree       Woman   
1        Cambridge    [8, 11)     [5, 8)   College degree  Non-binary   
2      Chattanooga     [2, 5)     [2, 5)   College degree       Woman   
3        Milwaukee    [8, 11)     [5, 8)   College degree       Woman   
4       Greenville    [8, 11)     [5, 8)   College degree       Woman   
...            ...        ...        ...              ...         ...   
27920          NYC     [2, 5)     [2, 5)   College degree       Woman   
27921       Denver   [31, 41)   [21, 31)     Some college       Woman   
27922   Fort Wayne   [11, 21)   [11, 21)   College degree         Ma

## 5. Salary by State

In [515]:
top_five_industries = df['Industry'].value_counts().head().index.tolist()
top_five_industries

['Computing or Tech',
 'Education (Higher Education)',
 'Nonprofits',
 'Health care',
 'Government and Public Administration']

In [516]:
filtered_df = df[df['Industry'].isin(top_five_industries)]
# filtered_df

In [517]:
unnested_df = filtered_df.assign(State = filtered_df['State'].str.split(',')).explode('State')
unnested_df['State'] = unnested_df['State'].str.strip()
# unnested_df

In [1]:
grouped = unnested_df.groupby(['State', 'Industry'])['Salary'].mean().reset_index()
# grouped

NameError: name 'unnested_df' is not defined

In [519]:
pivoted = grouped.pivot(index = 'State', columns = 'Industry', values = 'Salary')
pivoted

Industry              Computing or Tech  Education (Higher Education)  \
State                                                                   
Alabama                   100240.000000                  59901.450000   
Alaska                    112500.000000                  71767.875000   
Arizona                   104242.105263                  62746.102564   
Arkansas                   81682.300000                  44726.666667   
California                155275.162822                  80739.906832   
Colorado                  127571.707483                  63277.727273   
Connecticut               128375.000000                  77238.733333   
Delaware                  116600.000000                  68036.250000   
District of Columbia      132327.929825                  73573.842105   
Florida                   113047.363636                  73820.363636   
Georgia                   119485.691358                  63479.960784   
Hawaii                              NaN                  87000.000000   
Idaho                     111527.692308                  61328.500000   
Illinois                  120210.315476                  70643.334474   
Indiana                    88566.647059                  61539.857143   
Iowa                       99729.736842                  62423.631579   
Kansas                     99565.052632                  49046.250000   
Kentucky                   92375.000000                  61653.636364   
Louisiana                  86080.000000                  55153.333333   
Maine                     103571.428571                  53535.933333   
Maryland                  117215.685185                  75494.186441   
Massachusetts             135267.875410                  75620.832461   
Michigan                  101197.232143                  71688.263889   
Minnesota                 107063.872093                  70004.327273   
Mississippi                94000.000000                  62928.571429   
Missouri                   96524.066667                  69210.000000   
Montana                    92142.857143                  34035.000000   
Nebraska                   90975.294118                  57108.473684   
Nevada                    141310.000000                  59200.000000   
New Hampshire              95881.111111                  73496.923077   
New Jersey                130173.146341                  71773.000000   
New Mexico                132200.000000                  64142.857143   
New York                  148108.458689                  78962.331034   
North Carolina            104944.854545                  62731.900000   
North Dakota               97880.000000                  55270.000000   
Ohio                      107116.696970                  56055.343284   
Oklahoma                   87929.500000                  51395.454545   
Oregon                    124768.000000                  65971.125000   
Pennsylvania              111372.043860                  62380.958333   
Rhode Island              113421.428571                  72592.666667   
South Carolina            109875.000000                  47712.666667   
South Dakota              115333.333333                  60350.000000   
Tennessee                 112847.058824                  77972.176471   
Texas                     114896.260090                  65351.591304   
Utah                      106103.020000                  68887.636364   
Vermont                   113805.555556                  83500.000000   
Virginia                  128080.932203                  64563.096154   
Washington                151949.035088                  70552.298246   
West Virginia             120500.000000                  48611.111111   
Wisconsin                 114441.321429                  57807.112903   
Wyoming                             NaN                  54606.000000   

Industry              Government and Public Administration    Health care  \
State                                                